import './globals.css'
import { Footer } from '@/components/Footer'
import { Navbar } from '@/components/Navbar'
import { Inter } from 'next/font/google'
import type { Metadata } from 'next'
import { cn } from '@/lib/utils'
import { Toaster } from '@/components/ui/toaster'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={cn(inter.className, 'flex min-h-[100vh] flex-col')}>
        <Navbar />
        <main className='flex flex-1 flex-col'>{children}</main>
        <Footer />
        <Toaster />
      </body>
    </html>
  )
}
